'use strict';

/**
 * BrainDuel question bank.
 *
 * 10 questions per topic per language (RO + EN) across 7 topics = 140 questions minimum.
 * Topics: general_knowledge, history, geography, gaming, music, technology, tv_series
 *
 * Each question object:
 * {
 *   id:           string   — unique identifier
 *   text:         string   — the question text
 *   answers:      string[] — exactly 4 answer options
 *   correctIndex: number   — 0-based index of the correct answer in `answers`
 *   topic:        string
 *   difficulty:   'easy' | 'medium' | 'hard'
 *   language:     'ro' | 'en'
 * }
 */

const questions = [
  // ════════════════════════════════════════════════════════════════════════════
  // GENERAL KNOWLEDGE — Romanian
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'gk_ro_001',
    text: 'Ce culori are steagul României?',
    answers: ['Verde, Alb, Roșu', 'Roșu, Galben, Albastru', 'Albastru, Galben, Roșu', 'Albastru, Alb, Roșu'],
    correctIndex: 2,
    topic: 'general_knowledge',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'gk_ro_002',
    text: 'Care este capitala Franței?',
    answers: ['Lyon', 'Marseille', 'Paris', 'Bordeaux'],
    correctIndex: 2,
    topic: 'general_knowledge',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'gk_ro_003',
    text: 'Care este cel mai mare ocean de pe Pământ?',
    answers: ['Oceanul Atlantic', 'Oceanul Indian', 'Oceanul Arctic', 'Oceanul Pacific'],
    correctIndex: 3,
    topic: 'general_knowledge',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'gk_ro_004',
    text: 'Câte continente are Pământul?',
    answers: ['5', '6', '7', '8'],
    correctIndex: 2,
    topic: 'general_knowledge',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'gk_ro_005',
    text: 'Cine a pictat Mona Lisa?',
    answers: ['Michelangelo', 'Raphael', 'Leonardo da Vinci', 'Botticelli'],
    correctIndex: 2,
    topic: 'general_knowledge',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'gk_ro_006',
    text: 'Care este formula chimică a apei?',
    answers: ['CO2', 'H2O2', 'NaCl', 'H2O'],
    correctIndex: 3,
    topic: 'general_knowledge',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'gk_ro_007',
    text: 'Câte coarde are o chitară clasică?',
    answers: ['4', '5', '6', '7'],
    correctIndex: 2,
    topic: 'general_knowledge',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'gk_ro_008',
    text: 'Câte planete are Sistemul Solar?',
    answers: ['7', '8', '9', '10'],
    correctIndex: 1,
    topic: 'general_knowledge',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'gk_ro_009',
    text: 'Care este cel mai dur mineral natural?',
    answers: ['Granit', 'Cuarț', 'Diamant', 'Safir'],
    correctIndex: 2,
    topic: 'general_knowledge',
    difficulty: 'medium',
    language: 'ro',
  },
  {
    id: 'gk_ro_010',
    text: 'Cine a scris Romeo și Julieta?',
    answers: ['Charles Dickens', 'William Shakespeare', 'Victor Hugo', 'Dante Alighieri'],
    correctIndex: 1,
    topic: 'general_knowledge',
    difficulty: 'easy',
    language: 'ro',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // GENERAL KNOWLEDGE — English
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'gk_en_001',
    text: 'What is the capital of Australia?',
    answers: ['Sydney', 'Melbourne', 'Brisbane', 'Canberra'],
    correctIndex: 3,
    topic: 'general_knowledge',
    difficulty: 'medium',
    language: 'en',
  },
  {
    id: 'gk_en_002',
    text: 'Which is the largest ocean on Earth?',
    answers: ['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean'],
    correctIndex: 3,
    topic: 'general_knowledge',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'gk_en_003',
    text: 'How many continents are there on Earth?',
    answers: ['5', '6', '7', '8'],
    correctIndex: 2,
    topic: 'general_knowledge',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'gk_en_004',
    text: 'Who painted the Sistine Chapel ceiling?',
    answers: ['Leonardo da Vinci', 'Raphael', 'Michelangelo', 'Botticelli'],
    correctIndex: 2,
    topic: 'general_knowledge',
    difficulty: 'medium',
    language: 'en',
  },
  {
    id: 'gk_en_005',
    text: 'What is the chemical symbol for gold?',
    answers: ['Go', 'Gd', 'Gl', 'Au'],
    correctIndex: 3,
    topic: 'general_knowledge',
    difficulty: 'medium',
    language: 'en',
  },
  {
    id: 'gk_en_006',
    text: 'Approximately how many bones are in the adult human body?',
    answers: ['156', '176', '206', '226'],
    correctIndex: 2,
    topic: 'general_knowledge',
    difficulty: 'medium',
    language: 'en',
  },
  {
    id: 'gk_en_007',
    text: 'Who wrote Romeo and Juliet?',
    answers: ['Charles Dickens', 'William Shakespeare', 'Victor Hugo', 'Dante Alighieri'],
    correctIndex: 1,
    topic: 'general_knowledge',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'gk_en_008',
    text: 'What is the hardest natural substance?',
    answers: ['Granite', 'Quartz', 'Diamond', 'Sapphire'],
    correctIndex: 2,
    topic: 'general_knowledge',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'gk_en_009',
    text: 'How many sides does a hexagon have?',
    answers: ['4', '5', '6', '7'],
    correctIndex: 2,
    topic: 'general_knowledge',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'gk_en_010',
    text: 'What is the approximate speed of light in km/s?',
    answers: ['199,792 km/s', '299,792 km/s', '399,792 km/s', '499,792 km/s'],
    correctIndex: 1,
    topic: 'general_knowledge',
    difficulty: 'hard',
    language: 'en',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // HISTORY — Romanian
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'hist_ro_001',
    text: 'În ce an a avut loc Marea Unire a României?',
    answers: ['1916', '1917', '1918', '1920'],
    correctIndex: 2,
    topic: 'history',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'hist_ro_002',
    text: 'Cine a fost primul Președinte al Statelor Unite ale Americii?',
    answers: ['Abraham Lincoln', 'Thomas Jefferson', 'Benjamin Franklin', 'George Washington'],
    correctIndex: 3,
    topic: 'history',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'hist_ro_003',
    text: 'În ce an a căzut Zidul Berlinului?',
    answers: ['1987', '1988', '1989', '1991'],
    correctIndex: 2,
    topic: 'history',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'hist_ro_004',
    text: 'Revoluția Franceză a început în ce an?',
    answers: ['1776', '1783', '1789', '1799'],
    correctIndex: 2,
    topic: 'history',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'hist_ro_005',
    text: 'Cine a construit Colosseumul din Roma?',
    answers: ['Grecii', 'Romanii', 'Etruścii', 'Fenicieni'],
    correctIndex: 1,
    topic: 'history',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'hist_ro_006',
    text: 'În ce an a izbucnit Primul Război Mondial?',
    answers: ['1910', '1912', '1914', '1916'],
    correctIndex: 2,
    topic: 'history',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'hist_ro_007',
    text: 'Ce civilizație a construit Machu Picchu?',
    answers: ['Aztecii', 'Mayașii', 'Incașii', 'Olmecii'],
    correctIndex: 2,
    topic: 'history',
    difficulty: 'medium',
    language: 'ro',
  },
  {
    id: 'hist_ro_008',
    text: 'Cine a fost ultimul faraon al Egiptului Antic?',
    answers: ['Nefertiti', 'Cleopatra', 'Hatshepsut', 'Tutankhamon'],
    correctIndex: 1,
    topic: 'history',
    difficulty: 'medium',
    language: 'ro',
  },
  {
    id: 'hist_ro_009',
    text: 'Napoleon Bonaparte a murit în exil pe insula?',
    answers: ['Corsica', 'Malta', 'Elba', 'Sfânta Elena'],
    correctIndex: 3,
    topic: 'history',
    difficulty: 'medium',
    language: 'ro',
  },
  {
    id: 'hist_ro_010',
    text: 'Cel mai lung conflict din istoria medievală europeană este Războiul de O Sută de Ani, care a durat de fapt câți ani?',
    answers: ['100', '112', '116', '98'],
    correctIndex: 2,
    topic: 'history',
    difficulty: 'hard',
    language: 'ro',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // HISTORY — English
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'hist_en_001',
    text: 'When did World War II end?',
    answers: ['1943', '1944', '1945', '1946'],
    correctIndex: 2,
    topic: 'history',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'hist_en_002',
    text: 'Who was the first man to walk on the Moon?',
    answers: ['Buzz Aldrin', 'Yuri Gagarin', 'Neil Armstrong', 'Michael Collins'],
    correctIndex: 2,
    topic: 'history',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'hist_en_003',
    text: 'In what year was the Magna Carta signed?',
    answers: ['1066', '1215', '1348', '1453'],
    correctIndex: 1,
    topic: 'history',
    difficulty: 'medium',
    language: 'en',
  },
  {
    id: 'hist_en_004',
    text: 'Who was the first female Prime Minister of the United Kingdom?',
    answers: ['Theresa May', 'Margaret Thatcher', 'Indira Gandhi', 'Angela Merkel'],
    correctIndex: 1,
    topic: 'history',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'hist_en_005',
    text: 'When did the Berlin Wall fall?',
    answers: ['1987', '1988', '1989', '1991'],
    correctIndex: 2,
    topic: 'history',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'hist_en_006',
    text: 'Who is credited with inventing the telephone?',
    answers: ['Thomas Edison', 'Nikola Tesla', 'Alexander Graham Bell', 'Guglielmo Marconi'],
    correctIndex: 2,
    topic: 'history',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'hist_en_007',
    text: 'When did the French Revolution begin?',
    answers: ['1776', '1783', '1789', '1799'],
    correctIndex: 2,
    topic: 'history',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'hist_en_008',
    text: 'What was the name of the ship that sank in 1912 after hitting an iceberg?',
    answers: ['Olympic', 'Britannic', 'Lusitania', 'Titanic'],
    correctIndex: 3,
    topic: 'history',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'hist_en_009',
    text: 'Who co-authored the Communist Manifesto with Friedrich Engels?',
    answers: ['Vladimir Lenin', 'Leon Trotsky', 'Karl Marx', 'Joseph Stalin'],
    correctIndex: 2,
    topic: 'history',
    difficulty: 'medium',
    language: 'en',
  },
  {
    id: 'hist_en_010',
    text: 'Which empire did Alexander the Great rule?',
    answers: ['Roman Empire', 'Persian Empire', 'Ottoman Empire', 'Macedonian Empire'],
    correctIndex: 3,
    topic: 'history',
    difficulty: 'medium',
    language: 'en',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // GEOGRAPHY — Romanian
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'geo_ro_001',
    text: 'Care este cel mai lung râu din lume?',
    answers: ['Amazon', 'Nil', 'Yangtze', 'Mississippi'],
    correctIndex: 1,
    topic: 'geography',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'geo_ro_002',
    text: 'Care este capitala Australiei?',
    answers: ['Sydney', 'Melbourne', 'Brisbane', 'Canberra'],
    correctIndex: 3,
    topic: 'geography',
    difficulty: 'medium',
    language: 'ro',
  },
  {
    id: 'geo_ro_003',
    text: 'Care este cel mai înalt munte din lume?',
    answers: ['K2', 'Kangchenjunga', 'Everest', 'Lhotse'],
    correctIndex: 2,
    topic: 'geography',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'geo_ro_004',
    text: 'Care este cel mai mare deșert cald din lume?',
    answers: ['Gobi', 'Kalahari', 'Sahara', 'Arabian'],
    correctIndex: 2,
    topic: 'geography',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'geo_ro_005',
    text: 'Care este capitala Japoniei?',
    answers: ['Osaka', 'Kyoto', 'Hiroshima', 'Tokyo'],
    correctIndex: 3,
    topic: 'geography',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'geo_ro_006',
    text: 'Pe ce continent se află Egipt?',
    answers: ['Asia', 'Europa', 'Africa', 'America de Nord'],
    correctIndex: 2,
    topic: 'geography',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'geo_ro_007',
    text: 'Care este cel mai adânc lac din lume?',
    answers: ['Lacul Superior', 'Lacul Victoria', 'Lacul Titicaca', 'Lacul Baikal'],
    correctIndex: 3,
    topic: 'geography',
    difficulty: 'medium',
    language: 'ro',
  },
  {
    id: 'geo_ro_008',
    text: 'Care este capitala Braziliei?',
    answers: ['São Paulo', 'Rio de Janeiro', 'Salvador', 'Brasília'],
    correctIndex: 3,
    topic: 'geography',
    difficulty: 'medium',
    language: 'ro',
  },
  {
    id: 'geo_ro_009',
    text: 'Care este cel mai mic stat din lume ca suprafață?',
    answers: ['Monaco', 'San Marino', 'Vatican', 'Liechtenstein'],
    correctIndex: 2,
    topic: 'geography',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'geo_ro_010',
    text: 'Pe ce continent se află Munții Anzi?',
    answers: ['America de Nord', 'America de Sud', 'Africa', 'Asia'],
    correctIndex: 1,
    topic: 'geography',
    difficulty: 'easy',
    language: 'ro',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // GEOGRAPHY — English
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'geo_en_001',
    text: 'What is the capital of Canada?',
    answers: ['Toronto', 'Vancouver', 'Montreal', 'Ottawa'],
    correctIndex: 3,
    topic: 'geography',
    difficulty: 'medium',
    language: 'en',
  },
  {
    id: 'geo_en_002',
    text: 'What is the longest river in the world?',
    answers: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'],
    correctIndex: 1,
    topic: 'geography',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'geo_en_003',
    text: 'Which is the largest country in the world by area?',
    answers: ['China', 'USA', 'Canada', 'Russia'],
    correctIndex: 3,
    topic: 'geography',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'geo_en_004',
    text: 'What is the capital of Japan?',
    answers: ['Osaka', 'Kyoto', 'Hiroshima', 'Tokyo'],
    correctIndex: 3,
    topic: 'geography',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'geo_en_005',
    text: 'Which continent is Egypt on?',
    answers: ['Asia', 'Europe', 'Africa', 'North America'],
    correctIndex: 2,
    topic: 'geography',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'geo_en_006',
    text: 'Which is the deepest lake in the world?',
    answers: ['Lake Superior', 'Lake Victoria', 'Lake Titicaca', 'Lake Baikal'],
    correctIndex: 3,
    topic: 'geography',
    difficulty: 'medium',
    language: 'en',
  },
  {
    id: 'geo_en_007',
    text: 'What is the capital of Brazil?',
    answers: ['São Paulo', 'Rio de Janeiro', 'Salvador', 'Brasília'],
    correctIndex: 3,
    topic: 'geography',
    difficulty: 'medium',
    language: 'en',
  },
  {
    id: 'geo_en_008',
    text: 'What is the smallest country in the world by area?',
    answers: ['Monaco', 'San Marino', 'Vatican City', 'Liechtenstein'],
    correctIndex: 2,
    topic: 'geography',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'geo_en_009',
    text: 'On which continent are the Andes mountains located?',
    answers: ['North America', 'South America', 'Africa', 'Asia'],
    correctIndex: 1,
    topic: 'geography',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'geo_en_010',
    text: 'Which ocean is the largest?',
    answers: ['Atlantic', 'Indian', 'Arctic', 'Pacific'],
    correctIndex: 3,
    topic: 'geography',
    difficulty: 'easy',
    language: 'en',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // GAMING — Romanian
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'game_ro_001',
    text: 'Cine este protagonistul din seria The Legend of Zelda?',
    answers: ['Zelda', 'Ganon', 'Link', 'Impa'],
    correctIndex: 2,
    topic: 'gaming',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'game_ro_002',
    text: 'În ce joc apare personajul Master Chief?',
    answers: ['Gears of War', 'Halo', 'Call of Duty', 'Destiny'],
    correctIndex: 1,
    topic: 'gaming',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'game_ro_003',
    text: 'Ce companie a creat jocul Minecraft?',
    answers: ['EA Games', 'Ubisoft', 'Mojang', 'Valve'],
    correctIndex: 2,
    topic: 'gaming',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'game_ro_004',
    text: 'În ce joc apare personajul Lara Croft?',
    answers: ['Uncharted', 'Tomb Raider', 'Prince of Persia', 'Assassin\'s Creed'],
    correctIndex: 1,
    topic: 'gaming',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'game_ro_005',
    text: 'Ce joc are motto-ul "War. War never changes."?',
    answers: ['Battlefield', 'Halo', 'Fallout', 'Doom'],
    correctIndex: 2,
    topic: 'gaming',
    difficulty: 'medium',
    language: 'ro',
  },
  {
    id: 'game_ro_006',
    text: 'Ce culoare este personajul Pac-Man?',
    answers: ['Roșu', 'Alb', 'Galben', 'Verde'],
    correctIndex: 2,
    topic: 'gaming',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'game_ro_007',
    text: 'Care a fost primul battle royale major care a popularizat genul?',
    answers: ['Fortnite', 'PUBG', 'Apex Legends', 'H1Z1'],
    correctIndex: 1,
    topic: 'gaming',
    difficulty: 'medium',
    language: 'ro',
  },
  {
    id: 'game_ro_008',
    text: 'Ce joc are personajul Cloud Strife?',
    answers: ['Final Fantasy VI', 'Final Fantasy VII', 'Kingdom Hearts', 'Crisis Core'],
    correctIndex: 1,
    topic: 'gaming',
    difficulty: 'medium',
    language: 'ro',
  },
  {
    id: 'game_ro_009',
    text: 'În ce joc joci ca Commander Shepard?',
    answers: ['Star Wars Jedi: Fallen Order', 'Destiny', 'Mass Effect', 'Anthem'],
    correctIndex: 2,
    topic: 'gaming',
    difficulty: 'medium',
    language: 'ro',
  },
  {
    id: 'game_ro_010',
    text: 'În ce an a fost lansat primul joc Pokémon?',
    answers: ['1994', '1995', '1996', '1997'],
    correctIndex: 2,
    topic: 'gaming',
    difficulty: 'medium',
    language: 'ro',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // GAMING — English
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'game_en_001',
    text: 'Who is the protagonist of The Legend of Zelda series?',
    answers: ['Zelda', 'Ganon', 'Link', 'Impa'],
    correctIndex: 2,
    topic: 'gaming',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'game_en_002',
    text: 'What company made Minecraft?',
    answers: ['EA Games', 'Ubisoft', 'Mojang', 'Valve'],
    correctIndex: 2,
    topic: 'gaming',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'game_en_003',
    text: 'In which game does Master Chief appear?',
    answers: ['Gears of War', 'Halo', 'Call of Duty', 'Destiny'],
    correctIndex: 1,
    topic: 'gaming',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'game_en_004',
    text: 'What is the best-selling video game of all time?',
    answers: ['Tetris', 'GTA V', 'Minecraft', 'Wii Sports'],
    correctIndex: 2,
    topic: 'gaming',
    difficulty: 'medium',
    language: 'en',
  },
  {
    id: 'game_en_005',
    text: 'Which game features Lara Croft as the protagonist?',
    answers: ['Uncharted', 'Tomb Raider', 'Prince of Persia', 'Assassin\'s Creed'],
    correctIndex: 1,
    topic: 'gaming',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'game_en_006',
    text: 'What color is Pac-Man?',
    answers: ['Red', 'White', 'Yellow', 'Green'],
    correctIndex: 2,
    topic: 'gaming',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'game_en_007',
    text: 'In which game do you play as Commander Shepard?',
    answers: ['Star Wars Jedi: Fallen Order', 'Destiny', 'Mass Effect', 'Anthem'],
    correctIndex: 2,
    topic: 'gaming',
    difficulty: 'medium',
    language: 'en',
  },
  {
    id: 'game_en_008',
    text: 'What does "NPC" stand for in gaming?',
    answers: ['New Player Character', 'Non-Playable Content', 'Non-Player Character', 'Net Player Control'],
    correctIndex: 2,
    topic: 'gaming',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'game_en_009',
    text: 'Which game franchise features a character named Solid Snake?',
    answers: ['Splinter Cell', 'Metal Gear', 'Hitman', 'Deus Ex'],
    correctIndex: 1,
    topic: 'gaming',
    difficulty: 'medium',
    language: 'en',
  },
  {
    id: 'game_en_010',
    text: 'What year was the first Pokémon game released?',
    answers: ['1994', '1995', '1996', '1997'],
    correctIndex: 2,
    topic: 'gaming',
    difficulty: 'medium',
    language: 'en',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // MUSIC — Romanian
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'music_ro_001',
    text: 'Cine a compus Simfonia nr. 9 în re minor?',
    answers: ['Mozart', 'Bach', 'Beethoven', 'Chopin'],
    correctIndex: 2,
    topic: 'music',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'music_ro_002',
    text: 'Din ce oraș era trupa The Beatles?',
    answers: ['Londra', 'Manchester', 'Liverpool', 'Birmingham'],
    correctIndex: 2,
    topic: 'music',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'music_ro_003',
    text: 'Cine este supranumit "Regina Popului"?',
    answers: ['Britney Spears', 'Lady Gaga', 'Madonna', 'Mariah Carey'],
    correctIndex: 2,
    topic: 'music',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'music_ro_004',
    text: 'Ce instrument cântă Yo-Yo Ma?',
    answers: ['Vioară', 'Violoncel', 'Contrabas', 'Viola'],
    correctIndex: 1,
    topic: 'music',
    difficulty: 'medium',
    language: 'ro',
  },
  {
    id: 'music_ro_005',
    text: 'Cine a compus baletul Lacul Lebedelor?',
    answers: ['Brahms', 'Dvorak', 'Vivaldi', 'Ceaikovski'],
    correctIndex: 3,
    topic: 'music',
    difficulty: 'medium',
    language: 'ro',
  },
  {
    id: 'music_ro_006',
    text: 'Ce artist are albumul emblematic "Thriller"?',
    answers: ['Prince', 'Michael Jackson', 'Whitney Houston', 'Stevie Wonder'],
    correctIndex: 1,
    topic: 'music',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'music_ro_007',
    text: 'Câte clape are un pian standard?',
    answers: ['72', '76', '84', '88'],
    correctIndex: 3,
    topic: 'music',
    difficulty: 'medium',
    language: 'ro',
  },
  {
    id: 'music_ro_008',
    text: 'Care este cel mai bine vândut album din toate timpurile?',
    answers: ['Back in Black — AC/DC', 'The Dark Side of the Moon — Pink Floyd', 'Thriller — Michael Jackson', 'Hotel California — Eagles'],
    correctIndex: 2,
    topic: 'music',
    difficulty: 'medium',
    language: 'ro',
  },
  {
    id: 'music_ro_009',
    text: 'Trupa Metallica face parte din ce gen muzical?',
    answers: ['Punk Rock', 'Heavy Metal', 'Grunge', 'Alternative Rock'],
    correctIndex: 1,
    topic: 'music',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'music_ro_010',
    text: 'Cine a cântat piesa "Bohemian Rhapsody"?',
    answers: ['Led Zeppelin', 'Deep Purple', 'Queen', 'Aerosmith'],
    correctIndex: 2,
    topic: 'music',
    difficulty: 'easy',
    language: 'ro',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // MUSIC — English
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'music_en_001',
    text: 'Who composed the 9th Symphony in D minor?',
    answers: ['Mozart', 'Bach', 'Beethoven', 'Chopin'],
    correctIndex: 2,
    topic: 'music',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'music_en_002',
    text: 'What city were The Beatles from?',
    answers: ['London', 'Manchester', 'Liverpool', 'Birmingham'],
    correctIndex: 2,
    topic: 'music',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'music_en_003',
    text: 'Who is known as the "Queen of Pop"?',
    answers: ['Britney Spears', 'Lady Gaga', 'Madonna', 'Mariah Carey'],
    correctIndex: 2,
    topic: 'music',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'music_en_004',
    text: 'What instrument does Yo-Yo Ma play?',
    answers: ['Violin', 'Cello', 'Double Bass', 'Viola'],
    correctIndex: 1,
    topic: 'music',
    difficulty: 'medium',
    language: 'en',
  },
  {
    id: 'music_en_005',
    text: 'Which artist released the iconic album "Thriller"?',
    answers: ['Prince', 'Michael Jackson', 'Whitney Houston', 'Stevie Wonder'],
    correctIndex: 1,
    topic: 'music',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'music_en_006',
    text: 'How many keys does a standard piano have?',
    answers: ['72', '76', '84', '88'],
    correctIndex: 3,
    topic: 'music',
    difficulty: 'medium',
    language: 'en',
  },
  {
    id: 'music_en_007',
    text: 'Who sang "Bohemian Rhapsody"?',
    answers: ['Led Zeppelin', 'Deep Purple', 'Queen', 'Aerosmith'],
    correctIndex: 2,
    topic: 'music',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'music_en_008',
    text: 'What genre is Metallica?',
    answers: ['Punk Rock', 'Heavy Metal', 'Grunge', 'Alternative Rock'],
    correctIndex: 1,
    topic: 'music',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'music_en_009',
    text: 'Which artist had the most Grammy wins as of 2023?',
    answers: ['Taylor Swift', 'Adele', 'Beyoncé', 'Jay-Z'],
    correctIndex: 2,
    topic: 'music',
    difficulty: 'hard',
    language: 'en',
  },
  {
    id: 'music_en_010',
    text: 'What band did Freddie Mercury front?',
    answers: ['Led Zeppelin', 'Deep Purple', 'Queen', 'Aerosmith'],
    correctIndex: 2,
    topic: 'music',
    difficulty: 'easy',
    language: 'en',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // TECHNOLOGY — Romanian
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'tech_ro_001',
    text: 'Cine a fondat compania Apple?',
    answers: ['Bill Gates și Paul Allen', 'Steve Jobs și Steve Wozniak', 'Larry Page și Sergey Brin', 'Mark Zuckerberg'],
    correctIndex: 1,
    topic: 'technology',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'tech_ro_002',
    text: 'Ce înseamnă acronimul "WWW"?',
    answers: ['World Wide Web', 'Wireless World Web', 'Wide Web World', 'Web Wide World'],
    correctIndex: 0,
    topic: 'technology',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'tech_ro_003',
    text: 'Ce limbaj de programare a creat Guido van Rossum?',
    answers: ['Ruby', 'Perl', 'Python', 'Java'],
    correctIndex: 2,
    topic: 'technology',
    difficulty: 'medium',
    language: 'ro',
  },
  {
    id: 'tech_ro_004',
    text: 'Ce înseamnă acronimul "HTML"?',
    answers: ['HyperText Markup Language', 'High Text Markup Language', 'HyperTransfer Markup Language', 'Home Tool Markup Language'],
    correctIndex: 0,
    topic: 'technology',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'tech_ro_005',
    text: 'Cine a fondat Microsoft?',
    answers: ['Steve Jobs și Steve Wozniak', 'Larry Page și Sergey Brin', 'Bill Gates și Paul Allen', 'Jack Dorsey și Evan Williams'],
    correctIndex: 2,
    topic: 'technology',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'tech_ro_006',
    text: 'Care este sistemul de operare al iPhone-ului?',
    answers: ['Android', 'Windows Mobile', 'iOS', 'HarmonyOS'],
    correctIndex: 2,
    topic: 'technology',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'tech_ro_007',
    text: 'Ce companie a dezvoltat sistemul de operare Android?',
    answers: ['Apple', 'Microsoft', 'Samsung', 'Google'],
    correctIndex: 3,
    topic: 'technology',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'tech_ro_008',
    text: 'Câți biți are un byte?',
    answers: ['4', '8', '16', '32'],
    correctIndex: 1,
    topic: 'technology',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'tech_ro_009',
    text: 'Ce înseamnă acronimul "CPU"?',
    answers: ['Central Power Unit', 'Core Processing Unit', 'Central Processing Unit', 'Computer Power Unit'],
    correctIndex: 2,
    topic: 'technology',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'tech_ro_010',
    text: 'În ce an a fost lansat primul iPhone?',
    answers: ['2005', '2006', '2007', '2008'],
    correctIndex: 2,
    topic: 'technology',
    difficulty: 'medium',
    language: 'ro',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // TECHNOLOGY — English
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'tech_en_001',
    text: 'Who founded Apple?',
    answers: ['Bill Gates and Paul Allen', 'Steve Jobs and Steve Wozniak', 'Larry Page and Sergey Brin', 'Mark Zuckerberg'],
    correctIndex: 1,
    topic: 'technology',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'tech_en_002',
    text: 'What does "WWW" stand for?',
    answers: ['World Wide Web', 'Wireless World Web', 'Wide Web World', 'Web Wide World'],
    correctIndex: 0,
    topic: 'technology',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'tech_en_003',
    text: 'Who created the Python programming language?',
    answers: ['James Gosling', 'Bjarne Stroustrup', 'Guido van Rossum', 'Brendan Eich'],
    correctIndex: 2,
    topic: 'technology',
    difficulty: 'medium',
    language: 'en',
  },
  {
    id: 'tech_en_004',
    text: 'What does HTML stand for?',
    answers: ['HyperText Markup Language', 'High Text Markup Language', 'HyperTransfer Markup Language', 'Home Tool Markup Language'],
    correctIndex: 0,
    topic: 'technology',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'tech_en_005',
    text: 'Who founded Microsoft?',
    answers: ['Steve Jobs and Steve Wozniak', 'Larry Page and Sergey Brin', 'Bill Gates and Paul Allen', 'Jack Dorsey and Evan Williams'],
    correctIndex: 2,
    topic: 'technology',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'tech_en_006',
    text: 'What operating system does the iPhone use?',
    answers: ['Android', 'Windows Mobile', 'iOS', 'HarmonyOS'],
    correctIndex: 2,
    topic: 'technology',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'tech_en_007',
    text: 'How many bits are in a byte?',
    answers: ['4', '8', '16', '32'],
    correctIndex: 1,
    topic: 'technology',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'tech_en_008',
    text: 'What does CPU stand for?',
    answers: ['Central Power Unit', 'Core Processing Unit', 'Central Processing Unit', 'Computer Power Unit'],
    correctIndex: 2,
    topic: 'technology',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'tech_en_009',
    text: 'Which company developed Android?',
    answers: ['Apple', 'Microsoft', 'Samsung', 'Google'],
    correctIndex: 3,
    topic: 'technology',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'tech_en_010',
    text: 'What year was the first iPhone released?',
    answers: ['2005', '2006', '2007', '2008'],
    correctIndex: 2,
    topic: 'technology',
    difficulty: 'medium',
    language: 'en',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // TV SERIES — Romanian
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'tv_ro_001',
    text: 'Cine ucide pe regele Joffrey Baratheon în Game of Thrones?',
    answers: ['Tyrion Lannister', 'Cersei Lannister', 'Olenna Tyrell', 'Petyr Baelish'],
    correctIndex: 2,
    topic: 'tv_series',
    difficulty: 'hard',
    language: 'ro',
  },
  {
    id: 'tv_ro_002',
    text: 'Câte sezoane are Breaking Bad?',
    answers: ['4', '5', '6', '7'],
    correctIndex: 1,
    topic: 'tv_series',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'tv_ro_003',
    text: 'Cine joacă rolul lui Walter White în Breaking Bad?',
    answers: ['Aaron Paul', 'Bryan Cranston', 'Bob Odenkirk', 'Dean Norris'],
    correctIndex: 1,
    topic: 'tv_series',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'tv_ro_004',
    text: 'În ce oraș se petrece acțiunea din serialul Friends?',
    answers: ['Los Angeles', 'Chicago', 'New York', 'Boston'],
    correctIndex: 2,
    topic: 'tv_series',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'tv_ro_005',
    text: 'Cum se numește cafeneaua frecventată de personajele din Friends?',
    answers: ['The Brew', 'Central Perk', 'Java Junction', 'Café Nervosa'],
    correctIndex: 1,
    topic: 'tv_series',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'tv_ro_006',
    text: 'Câte sezoane are Game of Thrones?',
    answers: ['6', '7', '8', '9'],
    correctIndex: 2,
    topic: 'tv_series',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'tv_ro_007',
    text: 'În ce an se petrece acțiunea din Stranger Things, sezonul 1?',
    answers: ['1980', '1981', '1983', '1985'],
    correctIndex: 2,
    topic: 'tv_series',
    difficulty: 'medium',
    language: 'ro',
  },
  {
    id: 'tv_ro_008',
    text: 'Care este prenumele real al lui Heisenberg în Breaking Bad?',
    answers: ['Jesse', 'Hank', 'Walter', 'Saul'],
    correctIndex: 2,
    topic: 'tv_series',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'tv_ro_009',
    text: 'Cum se numea compania din serialul The Office (versiunea americană)?',
    answers: ['Initech', 'Dunder Mifflin', 'Wernham Hogg', 'Vandelay Industries'],
    correctIndex: 1,
    topic: 'tv_series',
    difficulty: 'easy',
    language: 'ro',
  },
  {
    id: 'tv_ro_010',
    text: 'Cine este tatăl adevărat al lui Jon Snow în Game of Thrones?',
    answers: ['Ned Stark', 'Robert Baratheon', 'Rhaegar Targaryen', 'Stannis Baratheon'],
    correctIndex: 2,
    topic: 'tv_series',
    difficulty: 'medium',
    language: 'ro',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // TV SERIES — English
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'tv_en_001',
    text: 'How many seasons does Breaking Bad have?',
    answers: ['4', '5', '6', '7'],
    correctIndex: 1,
    topic: 'tv_series',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'tv_en_002',
    text: 'Who plays Walter White in Breaking Bad?',
    answers: ['Aaron Paul', 'Bryan Cranston', 'Bob Odenkirk', 'Dean Norris'],
    correctIndex: 1,
    topic: 'tv_series',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'tv_en_003',
    text: 'What city is Friends set in?',
    answers: ['Los Angeles', 'Chicago', 'New York City', 'Boston'],
    correctIndex: 2,
    topic: 'tv_series',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'tv_en_004',
    text: 'What is the name of the coffee shop in Friends?',
    answers: ['The Brew', 'Central Perk', 'Java Junction', 'Café Nervosa'],
    correctIndex: 1,
    topic: 'tv_series',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'tv_en_005',
    text: 'How many seasons does Game of Thrones have?',
    answers: ['6', '7', '8', '9'],
    correctIndex: 2,
    topic: 'tv_series',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'tv_en_006',
    text: 'In Stranger Things season 1, what year is the setting?',
    answers: ['1980', '1981', '1983', '1985'],
    correctIndex: 2,
    topic: 'tv_series',
    difficulty: 'medium',
    language: 'en',
  },
  {
    id: 'tv_en_007',
    text: "What is Heisenberg's real name in Breaking Bad?",
    answers: ['Jesse Pinkman', 'Hank Schrader', 'Walter White', 'Saul Goodman'],
    correctIndex: 2,
    topic: 'tv_series',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'tv_en_008',
    text: 'What is the name of the company in The Office (US version)?',
    answers: ['Initech', 'Dunder Mifflin', 'Wernham Hogg', 'Vandelay Industries'],
    correctIndex: 1,
    topic: 'tv_series',
    difficulty: 'easy',
    language: 'en',
  },
  {
    id: 'tv_en_009',
    text: "Who is Jon Snow's real father in Game of Thrones?",
    answers: ['Ned Stark', 'Robert Baratheon', 'Rhaegar Targaryen', 'Stannis Baratheon'],
    correctIndex: 2,
    topic: 'tv_series',
    difficulty: 'medium',
    language: 'en',
  },
  {
    id: 'tv_en_010',
    text: 'In which country is The Office (US version) set?',
    answers: ['United Kingdom', 'Canada', 'Australia', 'United States'],
    correctIndex: 3,
    topic: 'tv_series',
    difficulty: 'easy',
    language: 'en',
  },
];

module.exports = { questions };
